### ISSUE TITLE
How to achieve fluid flow like stream.

### ISSUE THREAD

**Issue by ueyudiud** [ueyudiud/FLE#2]
The maximum distance of fluid flowing in Minecraft is 16 meters.
So is there any way to make this distance longer? I tried override BlockState but it seems might lost some compatibility in other uses of fluid block.

**Comment by 3TUSK** [comment]
https://github.com/delvr/Streams

**Comment by ueyudiud** [comment]
For one year later, I've already build a new world block metadata system which can help me solve this problem. Now this issue has been solved. Thanks for your helps.
